// =============================================================================
// Frozen 機制使用模式範本
// 展示 [Frozen] 屬性在 AutoFixture + NSubstitute 整合中的各種使用模式
// =============================================================================

using AutoFixture;
using AutoFixture.AutoNSubstitute;
using AutoFixture.Xunit2;
using FluentAssertions;
using NSubstitute;
using Xunit;

namespace MyProject.Tests.FrozenPatterns;

#region 基礎 Frozen 模式

// =============================================================================
// 基礎 Frozen 模式
// =============================================================================

/// <summary>
/// 示範 Frozen 屬性的基本用法
/// </summary>
public class BasicFrozenPatternTests
{
    /// <summary>
    /// 基本模式：凍結相依性並設定行為
    /// </summary>
    /// <remarks>
    /// [Frozen] 確保 repository 和 sut 內部使用的是同一個實例
    /// </remarks>
    [Theory]
    [AutoNSubstituteData]
    public async Task BasicFrozenPattern(
        [Frozen] IOrderRepository repository,  // 凍結這個相依性
        OrderService sut)                       // SUT 會使用同一個 repository
    {
        // Arrange
        var orderId = 1;
        var expectedOrder = new Order { Id = orderId, Status = "Active" };
        
        // 設定凍結實例的行為
        repository.GetByIdAsync(orderId).Returns(expectedOrder);

        // Act
        var result = await sut.GetOrderAsync(orderId);

        // Assert
        result.Should().BeEquivalentTo(expectedOrder);
        
        // 驗證呼叫（因為是同一個實例，驗證會成功）
        await repository.Received(1).GetByIdAsync(orderId);
    }

    /// <summary>
    /// ❌ 錯誤模式：Frozen 參數在 SUT 之後
    /// </summary>
    /// <remarks>
    /// 當 Frozen 參數在 SUT 之後，SUT 會使用不同的 repository 實例
    /// 這個測試展示錯誤的模式
    /// </remarks>
    // [Theory]
    // [AutoNSubstituteData]
    // public async Task WrongFrozenOrder(
    //     OrderService sut,                       // ❌ SUT 先建立
    //     [Frozen] IOrderRepository repository)   // ❌ 太晚凍結，這是不同的實例
    // {
    //     // 這個 repository 不是 sut 內部使用的那個
    //     repository.GetByIdAsync(Arg.Any<int>()).Returns(new Order());
    //     
    //     // sut 內部使用的是另一個 repository 實例
    //     // 所以這個設定不會生效！
    // }

    /// <summary>
    /// 參數順序的重要性
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task CorrectParameterOrder(
        [Frozen] IOrderRepository repository,   // 1. 先凍結相依性
        [Frozen] INotificationService notifier, // 2. 可以凍結多個
        [Frozen] ILogger<OrderService> logger,  // 3. 包括 ILogger
        OrderService sut)                        // 4. 最後才是 SUT
    {
        // Arrange
        repository.GetByIdAsync(Arg.Any<int>()).Returns(new Order { Id = 1 });
        notifier.SendAsync(Arg.Any<string>()).Returns(true);

        // Act
        var result = await sut.GetOrderAsync(1);

        // Assert
        result.Should().NotBeNull();
    }
}

#endregion

#region 多個 Frozen 相依性

// =============================================================================
// 多個 Frozen 相依性
// =============================================================================

/// <summary>
/// 示範凍結多個相依性的模式
/// </summary>
public class MultipleFrozenDependenciesTests
{
    /// <summary>
    /// 凍結多個相依性並分別設定行為
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task FreezeMultipleDependencies(
        [Frozen] IOrderRepository orderRepository,
        [Frozen] ICustomerRepository customerRepository,
        [Frozen] IInventoryService inventoryService,
        OrderProcessingService sut)
    {
        // Arrange
        var order = new Order { Id = 1, CustomerId = 100, ProductId = 200 };
        var customer = new Customer { Id = 100, Name = "Test Customer" };
        
        orderRepository.GetByIdAsync(1).Returns(order);
        customerRepository.GetByIdAsync(100).Returns(customer);
        inventoryService.CheckAvailabilityAsync(200).Returns(true);

        // Act
        var result = await sut.ProcessOrderAsync(1);

        // Assert
        result.Should().NotBeNull();
        result.CustomerName.Should().Be("Test Customer");
    }

    /// <summary>
    /// 部分凍結：只凍結需要設定行為的相依性
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task PartialFreeze(
        [Frozen] IOrderRepository repository,  // 只凍結這個
        OrderService sut)                       // 其他相依性自動產生但不凍結
    {
        // Arrange
        repository.GetByIdAsync(1).Returns(new Order { Id = 1 });

        // Act
        var result = await sut.GetOrderAsync(1);

        // Assert
        result.Should().NotBeNull();
        
        // 只需要驗證有設定行為的相依性
        await repository.Received(1).GetByIdAsync(1);
    }
}

#endregion

#region Frozen 與自動產生資料結合

// =============================================================================
// Frozen 與自動產生資料結合
// =============================================================================

/// <summary>
/// 示範 Frozen 相依性與自動產生資料的結合
/// </summary>
public class FrozenWithAutoGeneratedDataTests
{
    /// <summary>
    /// 自動產生測試資料並使用凍結的相依性
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task FrozenWithAutoGeneratedModel(
        [Frozen] IOrderRepository repository,
        OrderService sut,
        Order order)  // AutoFixture 自動產生
    {
        // Arrange
        // 使用自動產生的 order 物件
        repository.GetByIdAsync(order.Id).Returns(order);

        // Act
        var result = await sut.GetOrderAsync(order.Id);

        // Assert
        result.Should().NotBeNull();
        result.Id.Should().Be(order.Id);
    }

    /// <summary>
    /// 自動產生集合資料
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task FrozenWithAutoGeneratedCollection(
        [Frozen] IOrderRepository repository,
        OrderService sut,
        List<Order> orders)  // 自動產生 3 個 Order
    {
        // Arrange
        repository.GetAllAsync().Returns(orders);

        // Act
        var result = await sut.GetAllOrdersAsync();

        // Assert
        result.Should().HaveCount(3);  // AutoFixture 預設產生 3 個
    }

    /// <summary>
    /// 使用 CollectionSize 控制集合大小
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task FrozenWithCollectionSize(
        [Frozen] IOrderRepository repository,
        OrderService sut,
        [CollectionSize(10)] IEnumerable<Order> orders)
    {
        // Arrange
        repository.GetAllAsync().Returns(orders);

        // Act
        var result = await sut.GetAllOrdersAsync();

        // Assert
        result.Should().HaveCount(10);
    }
}

#endregion

#region Frozen 與 IFixture 結合

// =============================================================================
// Frozen 與 IFixture 結合
// =============================================================================

/// <summary>
/// 示範 Frozen 與 IFixture 的結合使用
/// </summary>
public class FrozenWithIFixtureTests
{
    /// <summary>
    /// 使用 IFixture 精確控制測試資料
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task FrozenWithIFixtureControl(
        IFixture fixture,
        [Frozen] IOrderRepository repository,
        OrderService sut)
    {
        // Arrange
        // 使用 fixture 精確控制資料
        var order = fixture.Build<Order>()
            .With(o => o.Id, 999)
            .With(o => o.Status, "Pending")
            .With(o => o.TotalAmount, 1500.00m)
            .Create();

        repository.GetByIdAsync(999).Returns(order);

        // Act
        var result = await sut.GetOrderAsync(999);

        // Assert
        result.Should().NotBeNull();
        result.Id.Should().Be(999);
        result.Status.Should().Be("Pending");
        result.TotalAmount.Should().Be(1500.00m);
    }

    /// <summary>
    /// 使用 IFixture 建立多個相關物件
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task FrozenWithRelatedObjects(
        IFixture fixture,
        [Frozen] IOrderRepository orderRepository,
        [Frozen] ICustomerRepository customerRepository,
        OrderProcessingService sut)
    {
        // Arrange
        var customerId = 100;
        
        var customer = fixture.Build<Customer>()
            .With(c => c.Id, customerId)
            .With(c => c.Name, "VIP Customer")
            .Create();

        var orders = fixture.Build<Order>()
            .With(o => o.CustomerId, customerId)
            .CreateMany(5);

        customerRepository.GetByIdAsync(customerId).Returns(customer);
        orderRepository.GetByCustomerIdAsync(customerId).Returns(orders);

        // Act
        var result = await sut.GetCustomerOrdersAsync(customerId);

        // Assert
        result.Should().HaveCount(5);
        result.All(o => o.CustomerId == customerId).Should().BeTrue();
    }
}

#endregion

#region Frozen 驗證模式

// =============================================================================
// Frozen 驗證模式
// =============================================================================

/// <summary>
/// 示範使用 Frozen 進行行為驗證
/// </summary>
public class FrozenVerificationPatternsTests
{
    /// <summary>
    /// 驗證方法被呼叫
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task VerifyMethodCalled(
        [Frozen] INotificationService notifier,
        [Frozen] IOrderRepository repository,
        OrderService sut,
        Order order)
    {
        // Arrange
        repository.GetByIdAsync(order.Id).Returns(order);
        notifier.SendAsync(Arg.Any<string>()).Returns(true);

        // Act
        await sut.ProcessAndNotifyAsync(order.Id);

        // Assert
        await notifier.Received(1).SendAsync(Arg.Any<string>());
    }

    /// <summary>
    /// 驗證方法未被呼叫
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task VerifyMethodNotCalled(
        [Frozen] INotificationService notifier,
        [Frozen] IOrderRepository repository,
        OrderService sut)
    {
        // Arrange
        repository.GetByIdAsync(Arg.Any<int>()).Returns((Order?)null);

        // Act
        await sut.ProcessAndNotifyAsync(999);

        // Assert
        // 當訂單不存在時，不應該發送通知
        await notifier.DidNotReceive().SendAsync(Arg.Any<string>());
    }

    /// <summary>
    /// 驗證傳入的參數
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task VerifyArgumentPassed(
        [Frozen] IOrderRepository repository,
        OrderService sut,
        Order order)
    {
        // Arrange
        repository.SaveAsync(Arg.Any<Order>()).Returns(true);

        // Act
        await sut.UpdateOrderStatusAsync(order, "Completed");

        // Assert
        await repository.Received(1).SaveAsync(Arg.Is<Order>(o =>
            o.Id == order.Id &&
            o.Status == "Completed"));
    }

    /// <summary>
    /// 捕獲並檢查參數
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task CaptureAndVerifyArgument(
        [Frozen] INotificationService notifier,
        [Frozen] IOrderRepository repository,
        OrderService sut,
        Order order)
    {
        // Arrange
        string? capturedMessage = null;
        repository.GetByIdAsync(order.Id).Returns(order);
        notifier.SendAsync(Arg.Do<string>(msg => capturedMessage = msg))
                .Returns(true);

        // Act
        await sut.ProcessAndNotifyAsync(order.Id);

        // Assert
        capturedMessage.Should().NotBeNull();
        capturedMessage.Should().Contain(order.Id.ToString());
    }
}

#endregion

#region 進階 Frozen 模式

// =============================================================================
// 進階 Frozen 模式
// =============================================================================

/// <summary>
/// 進階 Frozen 使用模式
/// </summary>
public class AdvancedFrozenPatternsTests
{
    /// <summary>
    /// 設定不同輸入的不同回傳值
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task DifferentReturnsForDifferentInputs(
        [Frozen] IOrderRepository repository,
        OrderService sut)
    {
        // Arrange
        var activeOrder = new Order { Id = 1, Status = "Active" };
        var completedOrder = new Order { Id = 2, Status = "Completed" };

        repository.GetByIdAsync(1).Returns(activeOrder);
        repository.GetByIdAsync(2).Returns(completedOrder);

        // Act
        var result1 = await sut.GetOrderAsync(1);
        var result2 = await sut.GetOrderAsync(2);

        // Assert
        result1.Status.Should().Be("Active");
        result2.Status.Should().Be("Completed");
    }

    /// <summary>
    /// 設定順序性回傳值
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task SequentialReturns(
        [Frozen] IOrderRepository repository,
        OrderService sut)
    {
        // Arrange
        var orders = new[]
        {
            new Order { Id = 1, Status = "Pending" },
            new Order { Id = 2, Status = "Processing" },
            new Order { Id = 3, Status = "Completed" }
        };

        repository.GetNextOrderAsync()
            .Returns(orders[0], orders[1], orders[2]);

        // Act
        var result1 = await sut.GetNextOrderAsync();
        var result2 = await sut.GetNextOrderAsync();
        var result3 = await sut.GetNextOrderAsync();

        // Assert
        result1.Status.Should().Be("Pending");
        result2.Status.Should().Be("Processing");
        result3.Status.Should().Be("Completed");
    }

    /// <summary>
    /// 模擬例外狀況
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task SimulateException(
        [Frozen] IOrderRepository repository,
        OrderService sut)
    {
        // Arrange
        repository.GetByIdAsync(Arg.Any<int>())
            .ThrowsAsync(new InvalidOperationException("Database connection failed"));

        // Act & Assert
        var exception = await Assert.ThrowsAsync<InvalidOperationException>(
            () => sut.GetOrderAsync(1));

        exception.Message.Should().Contain("Database connection failed");
    }

    /// <summary>
    /// 條件式回傳值
    /// </summary>
    [Theory]
    [AutoNSubstituteData]
    public async Task ConditionalReturns(
        [Frozen] IOrderRepository repository,
        OrderService sut)
    {
        // Arrange
        repository.GetByIdAsync(Arg.Is<int>(id => id > 0))
            .Returns(callInfo => new Order 
            { 
                Id = callInfo.Arg<int>(), 
                Status = "Found" 
            });

        repository.GetByIdAsync(Arg.Is<int>(id => id <= 0))
            .Returns((Order?)null);

        // Act
        var positiveResult = await sut.GetOrderAsync(5);
        var negativeResult = await sut.GetOrderAsync(-1);

        // Assert
        positiveResult.Should().NotBeNull();
        positiveResult!.Id.Should().Be(5);
        negativeResult.Should().BeNull();
    }
}

#endregion

#region 範例介面與類別

// =============================================================================
// 範例介面與類別（供上方測試使用）
// =============================================================================

public interface IOrderRepository
{
    Task<Order?> GetByIdAsync(int id);
    Task<IEnumerable<Order>> GetAllAsync();
    Task<IEnumerable<Order>> GetByCustomerIdAsync(int customerId);
    Task<Order?> GetNextOrderAsync();
    Task<bool> SaveAsync(Order order);
}

public interface ICustomerRepository
{
    Task<Customer?> GetByIdAsync(int id);
}

public interface INotificationService
{
    Task<bool> SendAsync(string message);
}

public interface IInventoryService
{
    Task<bool> CheckAvailabilityAsync(int productId);
}

public interface ILogger<T>
{
    void LogInformation(string message);
    void LogError(Exception ex, string message);
}

public class Order
{
    public int Id { get; set; }
    public int CustomerId { get; set; }
    public int ProductId { get; set; }
    public string Status { get; set; } = string.Empty;
    public decimal TotalAmount { get; set; }
}

public class Customer
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
}

public class OrderResult
{
    public int OrderId { get; set; }
    public string CustomerName { get; set; } = string.Empty;
}

public class OrderService
{
    private readonly IOrderRepository _repository;
    private readonly INotificationService? _notifier;

    public OrderService(
        IOrderRepository repository,
        INotificationService? notifier = null)
    {
        _repository = repository;
        _notifier = notifier;
    }

    public async Task<Order?> GetOrderAsync(int id)
    {
        return await _repository.GetByIdAsync(id);
    }

    public async Task<IEnumerable<Order>> GetAllOrdersAsync()
    {
        return await _repository.GetAllAsync();
    }

    public async Task<Order?> GetNextOrderAsync()
    {
        return await _repository.GetNextOrderAsync();
    }

    public async Task ProcessAndNotifyAsync(int orderId)
    {
        var order = await _repository.GetByIdAsync(orderId);
        if (order != null && _notifier != null)
        {
            await _notifier.SendAsync($"Order {orderId} processed");
        }
    }

    public async Task UpdateOrderStatusAsync(Order order, string status)
    {
        order.Status = status;
        await _repository.SaveAsync(order);
    }
}

public class OrderProcessingService
{
    private readonly IOrderRepository _orderRepository;
    private readonly ICustomerRepository _customerRepository;
    private readonly IInventoryService _inventoryService;

    public OrderProcessingService(
        IOrderRepository orderRepository,
        ICustomerRepository customerRepository,
        IInventoryService inventoryService)
    {
        _orderRepository = orderRepository;
        _customerRepository = customerRepository;
        _inventoryService = inventoryService;
    }

    public async Task<OrderResult?> ProcessOrderAsync(int orderId)
    {
        var order = await _orderRepository.GetByIdAsync(orderId);
        if (order == null) return null;

        var customer = await _customerRepository.GetByIdAsync(order.CustomerId);
        if (customer == null) return null;

        var available = await _inventoryService.CheckAvailabilityAsync(order.ProductId);
        if (!available) return null;

        return new OrderResult
        {
            OrderId = order.Id,
            CustomerName = customer.Name
        };
    }

    public async Task<IEnumerable<Order>> GetCustomerOrdersAsync(int customerId)
    {
        return await _orderRepository.GetByCustomerIdAsync(customerId);
    }
}

// AutoNSubstituteData 屬性（簡化版本，供本檔案範例使用）
public class AutoNSubstituteDataAttribute : AutoDataAttribute
{
    public AutoNSubstituteDataAttribute() : base(() => 
        new Fixture().Customize(new AutoNSubstituteCustomization()))
    {
    }
}

// CollectionSize 屬性（來自 autofixture-customization 技能）
[AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false)]
public class CollectionSizeAttribute : CustomizeAttribute
{
    private readonly int _size;

    public CollectionSizeAttribute(int size)
    {
        _size = size;
    }

    public override ICustomization GetCustomization(System.Reflection.ParameterInfo parameter)
    {
        return new CollectionSizeCustomization(parameter.ParameterType, _size);
    }

    private class CollectionSizeCustomization : ICustomization
    {
        private readonly Type _targetType;
        private readonly int _size;

        public CollectionSizeCustomization(Type targetType, int size)
        {
            _targetType = targetType;
            _size = size;
        }

        public void Customize(IFixture fixture)
        {
            fixture.RepeatCount = _size;
        }
    }
}

#endregion
