using System;
using System.Linq;
using System.Linq.Expressions;
using AwesomeAssertions;
using Xunit;

namespace DotNetTesting.ComplexObjectComparison.Templates;

/// <summary>
/// 欄位排除策略與擴充方法範本
/// 提供可重複使用的排除模式，減少測試程式碼重複
/// </summary>
public static class ExclusionStrategies
{
    #region 智慧型排除擴充方法

    /// <summary>
    /// 排除常見的自動生成欄位
    /// 包括：ID、時間戳記、版本號等
    /// </summary>
    public static EquivalencyOptions<T> ExcludingAutoGeneratedFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            // 排除以 "Generated" 開頭且以 "Id" 結尾的欄位
            .Excluding(ctx => ctx.Path.EndsWith("Id") &&
                            ctx.SelectedMemberInfo.Name.StartsWith("Generated"))
            // 排除所有以 "At" 結尾的時間欄位
            .Excluding(ctx => ctx.Path.EndsWith("At"))
            // 排除所有以 "Time" 結尾的欄位
            .Excluding(ctx => ctx.Path.EndsWith("Time"))
            // 排除包含 "Version" 的欄位（樂觀鎖版本號）
            .Excluding(ctx => ctx.Path.Contains("Version"))
            // 排除包含 "RowVersion" 的欄位（EF RowVersion）
            .Excluding(ctx => ctx.Path.Contains("RowVersion"))
            // 排除包含 "Timestamp" 的欄位
            .Excluding(ctx => ctx.Path.Contains("Timestamp"));
    }

    /// <summary>
    /// 排除稽核相關欄位
    /// 包括：建立者、建立時間、修改者、修改時間
    /// </summary>
    public static EquivalencyOptions<T> ExcludingAuditFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            .Excluding(ctx => ctx.Path.Contains("CreatedBy"))
            .Excluding(ctx => ctx.Path.Contains("CreatedAt"))
            .Excluding(ctx => ctx.Path.Contains("ModifiedBy"))
            .Excluding(ctx => ctx.Path.Contains("ModifiedAt"))
            .Excluding(ctx => ctx.Path.Contains("UpdatedBy"))
            .Excluding(ctx => ctx.Path.Contains("UpdatedAt"))
            .Excluding(ctx => ctx.Path.Contains("LastModified"));
    }

    /// <summary>
    /// 排除所有日期時間相關欄位
    /// </summary>
    public static EquivalencyOptions<T> ExcludingAllTimeFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            .Excluding(ctx => ctx.Path.EndsWith("At"))
            .Excluding(ctx => ctx.Path.EndsWith("Time"))
            .Excluding(ctx => ctx.Path.EndsWith("Date"))
            .Excluding(ctx => ctx.Path.Contains("DateTime"))
            .Excluding(ctx => ctx.Path.Contains("Timestamp"));
    }

    /// <summary>
    /// 組合：排除所有常見的自動欄位
    /// = ExcludingAutoGeneratedFields + ExcludingAuditFields
    /// </summary>
    public static EquivalencyOptions<T> ExcludingCommonAutoFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            .ExcludingAutoGeneratedFields()
            .ExcludingAuditFields();
    }

    /// <summary>
    /// 排除 Entity Framework 相關的追蹤欄位
    /// </summary>
    public static EquivalencyOptions<T> ExcludingEntityFrameworkFields<T>(
        this EquivalencyOptions<T> options)
    {
        return options
            .ExcludingMissingMembers()              // 排除 EF 額外屬性
            .Excluding(ctx => ctx.Path.Contains("Navigation"))  // 導航屬性
            .Excluding(ctx => ctx.Path.Contains("Proxy"))       // Proxy 屬性
            .ExcludingAutoGeneratedFields()
            .ExcludingAuditFields();
    }

    #endregion

    #region 效能最佳化工具

    /// <summary>
    /// 大量資料集的關鍵屬性快速比對
    /// 避免深度物件遍歷，只比對指定的關鍵屬性
    /// </summary>
    public static void AssertKeyPropertiesOnly<T>(
        T actual,
        T expected,
        params Expression<Func<T, object>>[] keySelectors)
    {
        if (keySelectors == null || keySelectors.Length == 0)
        {
            throw new ArgumentException("必須至少指定一個關鍵屬性", nameof(keySelectors));
        }

        foreach (var selector in keySelectors)
        {
            var actualValue = selector.Compile()(actual);
            var expectedValue = selector.Compile()(expected);

            actualValue.Should().Be(expectedValue,
                $"關鍵屬性 {GetPropertyName(selector)} 應該相符");
        }
    }

    /// <summary>
    /// 從 Expression 中提取屬性名稱
    /// </summary>
    private static string GetPropertyName<T>(Expression<Func<T, object>> expression)
    {
        return expression.Body switch
        {
            MemberExpression memberExpression => memberExpression.Member.Name,
            UnaryExpression { Operand: MemberExpression unaryMember } => unaryMember.Member.Name,
            _ => expression.ToString()
        };
    }

    #endregion

    #region 條件式排除擴充

    /// <summary>
    /// 根據條件決定是否排除特定屬性
    /// </summary>
    public static EquivalencyOptions<T> ExcludingWhen<T>(
        this EquivalencyOptions<T> options,
        Expression<Func<T, object>> propertySelector,
        bool condition)
    {
        return condition
            ? options.Excluding(propertySelector)
            : options;
    }

    /// <summary>
    /// 排除值為預設值的屬性
    /// </summary>
    public static EquivalencyOptions<T> ExcludingDefaultValues<T>(
        this EquivalencyOptions<T> options)
    {
        return options.Excluding(ctx =>
        {
            var value = ctx.SelectedMemberInfo.GetValue(ctx.Subject);
            if (value == null) return false;

            var type = value.GetType();
            var defaultValue = type.IsValueType ? Activator.CreateInstance(type) : null;

            return Equals(value, defaultValue);
        });
    }

    #endregion
}

#region 使用範例

/// <summary>
/// 排除策略的使用範例
/// </summary>
public class ExclusionStrategiesExamples
{
    #region Test Models

    public class UserEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;

        // 自動生成欄位
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public int Version { get; set; }
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();

        // 稽核欄位
        public string CreatedBy { get; set; } = string.Empty;
        public string? ModifiedBy { get; set; }
        public DateTime? LastModifiedAt { get; set; }
    }

    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public decimal Price { get; set; }
        public int StockQuantity { get; set; }

        // 時間戳記
        public DateTime CreatedTime { get; set; }
        public DateTime UpdatedTime { get; set; }
        public DateTime? DeletedAt { get; set; }
    }

    #endregion

    #region 範例 1: 基本智慧排除

    [Fact]
    public void Example1_使用智慧排除_簡化測試()
    {
        // Arrange
        var original = new UserEntity
        {
            Id = 1,
            Name = "John Doe",
            Email = "john@example.com",
            CreatedAt = DateTime.Now.AddDays(-1),
            UpdatedAt = DateTime.Now.AddDays(-1),
            Version = 1,
            CreatedBy = "system"
        };

        // Act
        var updated = UpdateUser(original);

        // Assert
        // 使用智慧排除，一行解決所有自動欄位
        updated.Should().BeEquivalentTo(original, options =>
            options.ExcludingCommonAutoFields()
        );
    }

    #endregion

    #region 範例 2: 組合多種排除策略

    [Fact]
    public void Example2_組合排除策略_處理複雜場景()
    {
        // Arrange
        var product = new Product
        {
            Id = 1,
            Name = "Laptop",
            Price = 999.99m,
            StockQuantity = 10
        };

        // Act
        var retrieved = GetProductFromDatabase(product.Id);

        // Assert
        // 組合多種策略
        retrieved.Should().BeEquivalentTo(product, options =>
            options.ExcludingAllTimeFields()           // 排除所有時間欄位
                   .ExcludingWhen(p => p.StockQuantity, // 條件式排除
                       condition: IsStockVolatile())
        );
    }

    #endregion

    #region 範例 3: EF 實體比對

    [Fact]
    public void Example3_EF實體比對_排除追蹤屬性()
    {
        // Arrange
        var expected = new UserEntity
        {
            Id = 1,
            Name = "John Doe",
            Email = "john@example.com"
        };

        // Act
        var actual = GetUserFromEFContext(1);

        // Assert
        // 使用 EF 專用排除
        actual.Should().BeEquivalentTo(expected, options =>
            options.ExcludingEntityFrameworkFields()
        );
    }

    #endregion

    #region 範例 4: 關鍵屬性快速比對

    [Fact]
    public void Example4_關鍵屬性驗證_提升效能()
    {
        // Arrange
        var expected = new Product
        {
            Id = 1,
            Name = "Laptop",
            Price = 999.99m,
            StockQuantity = 10,
            CreatedTime = DateTime.Now,
            UpdatedTime = DateTime.Now
        };

        // Act
        var actual = GetProduct(1);

        // Assert
        // 只驗證關鍵業務屬性，忽略時間戳記
        ExclusionStrategies.AssertKeyPropertiesOnly(
            actual,
            expected,
            p => p.Id,
            p => p.Name,
            p => p.Price,
            p => p.StockQuantity
        );
    }

    #endregion

    #region 範例 5: 條件式排除

    [Fact]
    public void Example5_條件式排除_動態決策()
    {
        // Arrange
        var product = new Product { Id = 1, Name = "Laptop", Price = 999 };
        var isIntegrationTest = IsRunningInIntegrationTestEnvironment();

        // Act
        var actual = GetProduct(1);

        // Assert
        // 根據測試環境動態決定排除策略
        actual.Should().BeEquivalentTo(product, options =>
            options.ExcludingAllTimeFields()
                   .ExcludingWhen(p => p.StockQuantity,
                       condition: isIntegrationTest) // 整合測試時庫存可能變動
        );
    }

    #endregion

    #region 範例 6: 排除預設值

    [Fact]
    public void Example6_排除預設值_處理未初始化屬性()
    {
        // Arrange
        var partialEntity = new UserEntity
        {
            Name = "John Doe",
            Email = "john@example.com"
            // Id, Version 等保持預設值
        };

        // Act
        var actual = CreateUser(partialEntity);

        // Assert
        // 排除預設值的屬性
        actual.Should().BeEquivalentTo(partialEntity, options =>
            options.ExcludingDefaultValues()
                   .ExcludingCommonAutoFields()
        );
    }

    #endregion

    #region Helper Methods

    private UserEntity UpdateUser(UserEntity user)
    {
        user.UpdatedAt = DateTime.Now;
        user.Version++;
        user.ModifiedBy = "admin";
        return user;
    }

    private Product GetProductFromDatabase(int id) => new()
    {
        Id = id,
        Name = "Laptop",
        Price = 999.99m,
        StockQuantity = 10,
        CreatedTime = DateTime.Now,
        UpdatedTime = DateTime.Now
    };

    private UserEntity GetUserFromEFContext(int id) => new()
    {
        Id = id,
        Name = "John Doe",
        Email = "john@example.com",
        CreatedAt = DateTime.Now,
        UpdatedAt = DateTime.Now,
        CreatedBy = "system"
    };

    private Product GetProduct(int id) => GetProductFromDatabase(id);

    private UserEntity CreateUser(UserEntity entity)
    {
        entity.Id = 1;
        entity.Version = 1;
        entity.CreatedAt = DateTime.Now;
        entity.CreatedBy = "system";
        return entity;
    }

    private bool IsStockVolatile() => false;
    private bool IsRunningInIntegrationTestEnvironment() => false;

    #endregion
}

#endregion
